### ISSUE TITLE
Typo on html2react for applying changes to page.js

### ISSUE THREAD

**Issue by damienmcd** [frontity/step-by-step-tutorial#13]
There is a typo on Part 7: html2react (https://tutorial.frontity.org/part7-finishing-touches/use-the-html2react-component) in the code block for applying the changes to page.js

I tried to create a PR but access was denied.

{post.title.rendered} and {post.content.rendered} should use 'page' instead of 'post'.
The variable is declared as `page` in previous sections of the tutorial.

![Screenshot 2021-02-10 at 14 22 01](https://user-images.githubusercontent.com/96244/107522774-f17cce00-6bab-11eb-8309-f32005335f84.png)

**Comment by mburridge** [comment]
Good catch @damienmcd. Thanks for that. I've fixed it.
