### ISSUE TITLE
Add a link to the final version of the project (codesanbox) in "The Project" section of te Homepage

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/step-by-step-tutorial#16]
Something like...

```
A preview of the finished site and the final version of the code can be seen in this CodeSandbox.
```

Pointing to https://codesandbox.io/s/github/frontity-demos/tutorial-hello-frontity

**Comment by mburridge** [comment]
Done: https://github.com/frontity/step-by-step-tutorial/commit/00e87de64d0f9a5b92155bae70b308073092e9c3#diff-a717e588bfc10f09b8b71fae18462c3d6a851d32a13ef21808082cc7f43b35d7R46-R48
