### ISSUE TITLE
Add explanations in the HomePage about the reference repo and the steps per commit resource

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/step-by-step-tutorial#17]
something like the explanations provided in the blog post...

```
As you work through the course you can compare your code at each stage with the corresponding commit in this repo, so you’ll always be sure that you’re on the right track.
```

**Comment by mburridge** [comment]
Done: https://github.com/frontity/step-by-step-tutorial/commit/00e87de64d0f9a5b92155bae70b308073092e9c3#diff-1109736d641543a1835a67b8c8104c638d997bb90d184a3f92ef0e04681e0133R1-R25
