### ISSUE TITLE
Fix link in Checking your progress

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/step-by-step-tutorial#18]
The text **_the ones in this commit._** should be **_the ones in these tagged commits per step._** and should point to https://github.com/frontity-demos/tutorial-hello-frontity/tags

> Check you're on the right track by comparing your changes with the ones in this commit.

**Comment by mburridge** [comment]
That's just an example box to illustrate the type of box that will be encountered at the end of each lesson. The link is deliberately just `#`.

**Comment by juanmaguitar** [comment]
Oh, I see. In that case, don't you think it would be better to show an image w/ a screenshot of that box? (so the link is not clickable and to avoid a possible confusion)

**Comment by mburridge** [comment]
Good idea 👌 - done!
