### ISSUE TITLE
"npm install dayjs" needs --save to be added to package.json

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/step-by-step-tutorial#6]
In In **[Formatting the date](https://tutorial.frontity.org/part3-displaying-posts/formatting-the-date)** the following command `npm install dayjs`

need to be like this `npm install dayjs --save` or `npm install dayjs -S`

so besides the installations of the package the dependency is automatically added to `package.json`
Without this argument the package is installed but not added as a dependency in the  `package.json`

**Comment by mburridge** [comment]
@juanmaguitar It seems since NPM v5 this is not necessary.

https://www.geeksforgeeks.org/what-is-the-meaning-of-save-for-npm-install/

**Comment by juanmaguitar** [comment]
>  It seems since NPM v5 this is not necessary.

Ups. I didn't know that.
You can close this issue then 👍
