### ISSUE TITLE
Some <Link> use "href" attribute instead of "link"

### ISSUE THREAD

**Issue by juanmaguitar** [frontity/step-by-step-tutorial#7]
The first time the `<Link>` component is introduced in the tutorial in the **[Use the <Link> component](https://tutorial.frontity.org/part2-adding-a-menu/use-the-link-component)** they're properly using the `link` attribute

```
 <nav>
        <Link link="/">Home</Link>
        <br />
        <Link link="/page/2">More posts</Link>
        <br />
        <Link link="/about-us">About Us</Link>
      </nav>
```

But from the **[Styled components](https://tutorial.frontity.org/part4-adding-styling/styled-components)** there are some links that use the `href` attribute that makes these links fail

```
 <nav>
    <Link href="/">Home</Link>
    <Link href="/page/2">More posts</Link>
    <Link link="/about-us">About Us</Link>
  </nav>
```

**Comment by mburridge** [comment]
Fixed.
